use_frameworks!

platform :ios, '13.0'

target 'DesignKit_Example' do
  pod 'DesignKit', :path => '../'

  target 'DesignKit_Tests' do
    inherit! :search_paths

    pod 'Quick', '= 3.0.0'
    pod 'Nimble', '= 13.7.1'
    
  end
end
